config/routes.rb
Rails.application.routes.draw do
  get '/cart', to: 'orders#cart', as: :cart
  get '/cart/add-item/:variant_id', to: 'orders#add_item_cart', as: :add_item_cart
  post '/cart/add-item', to: 'orders#add_item_cart', as: :add_item_cart_post
  get '/cart/remove-item/:variant_id', to: 'orders#remove_item_cart', as: :remove_item_cart
  patch '/cart', to: 'orders#update_cart', as: :update_cart
  get '/checkout', to: 'orders#checkout', as: :checkout
  patch '/checkout/:state', :to => 'orders#update_checkout', :as => :update_checkout
  get '/checkout/:state', :to => 'orders#checkout', :as => :checkout_state

  root to: "pages#home"
  mount Spree::Core::Engine, at: '/'

  resources :products
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

  get '/contact' => "pages#contact"
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Spree::Product.all.search(params[:search]).select{|product| product.images.present?&&(product.total_on_hand > 0)}
    @products = @products.select{|product| product.price >= params[:price_min].to_i} if params[:price_min].present?
    @products = @products.select{|product| product.price <= params[:price_max].to_i} if params[:price_max].present?
    @products = @products.select{|product| product.taxons.map(&:id).include?(params[:category].to_i)} if params[:category].present?
    @products = @products.paginate(page: params[:page], per_page: 9)
    @category = Spree::Taxon.find(params[:category]) if params[:category].present?
  end

  def show
    @product = Spree::Product.friendly.find(params[:id])
  end
end

app/views/products/index.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= render "shared/sidebar.html.erb" %>
      </div>
      <div class="col-sm-9 padding-right">
        <div class="features_items">
          <h2 class="title text-center">Features Items</h2>
          <% @products.each_slice(3) do |products| %>
            <div class="row">
              <% products.each do |product| %>
                <div class="col-sm-4">
                  <div class="product-image-wrapper">
                    <div class="single-products">
                      <div class="productinfo text-center">
                        <%= image_tag product.images[0].attachment.url(:product) %>
                        <h2><%= product.display_price %></h2>
                        <p><%= product.name.titleize %></p>
                        <%= link_to add_item_cart_path(product.master.id), class: 'btn btn-default add-to-cart' do %>
                          <i class="fa fa-shopping-cart"></i>Add to cart
                        <% end %>
                      </div>
                      <div class="product-overlay">
                        <div class="overlay-content">
                          <h2><%= product.display_price %></h2>
                          <p><%= link_to product.name.titleize, product %></p>
                          <%= link_to add_item_cart_path(product.master.id), class: 'btn btn-default add-to-cart' do %>
                            <i class="fa fa-shopping-cart"></i>Add to cart
                          <% end %>
                        </div>
                      </div>
                    </div>
                    <div class="choose">
                      <ul class="nav nav-pills nav-justified">
                        <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>

          <div class="products-pager" id="products-pager">
            <%= will_paginate @products, inner_window: 2, outer_window: 1 %>
          </div>
        </div>
        <%= render "shared/recomended.html.erb" %>
      </div>
    </div>
  </div>
</section>

app/views/products/show.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 padding-right">
        <div id="bc1" class="btn-group btn-breadcrumb">
          <a href="/" class="btn btn-default"><i class="fa fa-home"></i></a>
          <div class="btn btn-default">...</div>
          <% @product.taxons.each do |taxon| %>
            <%= link_to taxon.name, products_path(params.merge({category: taxon.id})), class: 'btn btn-default' %>
          <% end %>
        </div>
        <div class="product-details">
          <div class="col-sm-4">
            <div class="view-product">
              <%= link_to(@product.images[0].attachment.url(:product), class: 'jqzoom', rel: 'gal1', title: @product.name) do %>
                <%= image_tag @product.images[0].attachment.url(:product), class: 'main-image' %>
              <% end %>
              <h3>ZOOM</h3>
            </div>
            <div id="similar-product" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% @product.images.each_slice(3).with_index do |images, index| %>
                  <div class="item <% if index == 0 %>active<% end %>">
                    <% images.each do |image| %>
                      <%= link_to('javascript:void(0);', rel: "{gallery: 'gal1', smallimage: '#{image.attachment.url(:product)}',largeimage: '#{image.attachment.url(:large)}'}") do %>
                        <%= image_tag image.attachment.url(:small) %>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>

              <a class="left item-control" href="#similar-product" data-slide="prev"><i class="fa fa-angle-left"></i></a>
              <a class="right item-control" href="#similar-product" data-slide="next"><i class="fa fa-angle-right"></i></a>
            </div>
          </div>

          <div class="col-sm-8">
            <div class="product-information">
              <%= image_tag("product-details/new.jpg", class: "newarrival") %>
              <h2><%= @product.name %></h2>
              <p>Web ID: <%= @product.id %></p>
              <%= image_tag("product-details/rating.png") %>
              <%= form_for :order, url: add_item_cart_post_path do |f| %>
                <%= hidden_field_tag "variant_id", @product.master.id %>
                <span>
                  <span><%= @product.display_price %></span>
                  <label>Quantity:</label>
                  <%= number_field_tag :quantity, 1, :class => 'title', :min => 1 %>
                  <%= button_tag :class => 'btn btn-fefault cart', :id => 'add-to-cart-button', :type => :submit do %>
                    <i class="fa fa-shopping-cart"></i>
                    <%= Spree.t(:add_to_cart) %>
                  <% end %>
                </span>
              <% end %>
              <p><b>Availability:</b> <%= @product.availability %></p>
              <p><b>Condition:</b> New</p>
              <p><b>Brand:</b> E-SHOPPER</p>
              <a href=""><%= image_tag("product-details/share.png", class: "share img-responsice") %></a>
            </div>
          </div>
        </div>

        <div class="category-tab shop-details-tab">
          <div class="col-sm-12">
            <ul class="nav nav-tabs">
              <li><a href="#details" data-toggle="tab">Details</a></li>
              <li><a href="#companyprofile" data-toggle="tab">Company Profile</a></li>
              <li><a href="#tag" data-toggle="tab">Tag</a></li>
              <li class="active"><a href="#reviews" data-toggle="tab">Reviews (5)</a></li>
            </ul>
          </div>
          <div class="tab-content">
            <div class="tab-pane fade" id="details" >
              <div class="col-sm-12">
                <p><%= @product.description %></p>
              </div>
            </div>

            <div class="tab-pane fade" id="companyprofile" >
              <div class="col-sm-12">
                <p><b>BLANK</b></p>
              </div>
            </div>

            <div class="tab-pane fade" id="tag" >
              <div class="col-sm-12">
                <p>
                  <% @product.meta_keywords.scan(/#\w+/).flatten.each do |keyword| %>
                    <b><%= keyword %></b>
                  <% end %>
                </p>
              </div>
            </div>

            <div class="tab-pane fade active in" id="reviews" >
              <div class="col-sm-12">
                <ul>
                  <li><a href=""><i class="fa fa-user"></i>EUGEN</a></li>
                  <li><a href=""><i class="fa fa-clock-o"></i>12:41 PM</a></li>
                  <li><a href=""><i class="fa fa-calendar-o"></i>31 DEC 2014</a></li>
                </ul>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                <p><b>Write Your Review</b></p>

                <form action="#">
                  <span>
                    <input type="text" placeholder="Your Name"/>
                    <input type="email" placeholder="Email Address"/>
                  </span>
                  <textarea name="" ></textarea>
                  <b>Rating: </b> <%= image_tag("product-details/rating.png") %>
                  <button type="button" class="btn btn-default pull-right">
                    Submit
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <%= render "shared/recomended.html.erb" %>
      </div>
    </div>
  </div>
</section>
<script type="text/javascript">
  $(document).ready(function() {
    $('.jqzoom').jqzoom({
      zoomType: 'standard',
      lens:true,
      preloadImages: false,
      alwaysOn:false
    });
  });
</script>