config/routes.rb
Rails.application.routes.draw do
  get '/cart', to: 'orders#cart', as: :cart
  get '/cart/add-item/:variant_id', to: 'orders#add_item_cart', as: :add_item_cart
  post '/cart/add-item', to: 'orders#add_item_cart', as: :add_item_cart_post
  get '/cart/remove-item/:variant_id', to: 'orders#remove_item_cart', as: :remove_item_cart
  patch '/cart', to: 'orders#update_cart', as: :update_cart
  get '/checkout', to: 'orders#checkout', as: :checkout
  patch '/checkout/:state', :to => 'orders#update_checkout', :as => :update_checkout
  get '/checkout/:state', :to => 'orders#checkout', :as => :checkout_state

  root to: "pages#home"
  mount Spree::Core::Engine, at: '/'

  resources :products
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

  get '/contact' => "pages#contact"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpreeShop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header id="header">
      <div class="header_top">
        <div class="container">
          <div class="row">
            <div class="col-sm-6">
              <div class="contactinfo">
                <ul class="nav nav-pills">
                  <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                  <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="social-icons pull-right">
                <ul class="nav navbar-nav">
                  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                  <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                  <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                  <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="header-middle">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <div class="logo pull-left">
                <a href="/"><%= image_tag("home/logo.png") %></a>
              </div>
              <div class="btn-group pull-right">
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                    USA
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><a href="#">Canada</a></li>
                    <li><a href="#">UK</a></li>
                  </ul>
                </div>

                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                    DOLLAR
                    <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu">
                    <li><a href="#">Canadian Dollar</a></li>
                    <li><a href="#">Pound</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="shop-menu pull-right">
                <ul class="nav navbar-nav">
                  <li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
                  <li><%= link_to cart_path do %>
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge"><%= cart_items_count %></span>
                  <% end %></li>
                  <% if current_user %>
                    <li><a href="#"><i class="fa fa-user"></i> Account</a></li>
                    <% if current_user.has_spree_role? "admin" %>
                      <li> <%= link_to '/admin' do %><i class="fa fa-wrench"></i> Admin Panel<% end %></li>
                    <% end %>
                    <li><%= link_to destroy_user_session_path, :method => :delete do %><i class="fa fa-sign-out"></i> Log out<% end %><li>
                  <% else %>
                    <li><%= link_to new_user_registration_path do %><i class="fa fa-user"></i> Register<% end %></li>
                    <li><%= link_to new_user_session_path do %><i class="fa fa-lock"></i> Login<% end %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="header-bottom">
        <div class="container">
          <div class="row">
            <div class="col-sm-5">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
              </div>
              <div class="mainmenu pull-left">
                <ul class="nav navbar-nav collapse navbar-collapse">
                  <li><%= link_to "Home", root_url, class: "active" %></li>
                  <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                  <ul role="menu" class="sub-menu">
                    <li><a href="/products">Products</a></li>
                  </ul>
                  </li> 
                  <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                  <ul role="menu" class="sub-menu">
                    <li><a href="blog.html">Blog List</a></li>
                    <li><a href="blog-single.html">Blog Single</a></li>
                  </ul>
                  </li> 
                  <li><a href="/contact" data-no-turbolink='true'>Contact</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-7">
              <div class="search_box pull-right">
                <%= form_tag products_path, method: 'get', id: "searchform" do %>
                  <div class="input-group">
                    <%= text_field_tag  :search, params[:search], placeholder: 'Search...', class: 'search input pull-right', id: 's' %>
                    <span class="input-group-btn">
                      <button type="submit" class="btn"><i class="fa fa-search"></i></button>
                    </span>
                  </div>
                  <%= hidden_field_tag  :price_min, params[:price_min] || Spree::Price.min %>
                  <%= hidden_field_tag  :price_max, params[:price_max] || Spree::Price.max  %>
                  <%= hidden_field_tag  :category, params[:category] %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-default" id="nav"  role="navigation">
        <div class="container">
          <div class="row">
            <div class="navbar-header col-xs-12">
              <a class="navbar-brand col-sm-2 hidden-xs" href="/">
                <%= image_tag("home/logo.png") %>
              </a>
              <span class="navbar-text col-sm-9">
                <div class="search_box pull-right">
                  <%= form_tag products_path, method: 'get', id: "searchform" do %>
                    <div class="input-group">
                      <%= text_field_tag  :search, params[:search], placeholder: 'Search...', class: 'search input pull-right', id: 's' %>
                      <span class="input-group-btn">
                        <button type="submit" class="btn"><i class="fa fa-search"></i></button>
                      </span>
                    </div>
                    <%= hidden_field_tag  :price_min, params[:price_min] || Spree::Price.min %>
                    <%= hidden_field_tag  :price_max, params[:price_max] || Spree::Price.max  %>
                    <%= hidden_field_tag  :category, params[:category] %>
                  <% end %>
                </div>
              </span>
              <span class="col-sm-1 hidden-xs">
              <%= link_to cart_path do %>
                <i class="fa fa-shopping-cart fa-4x"></i>
                <span class="badge progress-bar-warning"><%= cart_items_count %></span>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <div id="notice"><%= notice %></div>
        <%= flash[:error] %>
      </div>
    </div>

    <%= yield %>

    <footer id="footer">
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
              <div class="companyinfo">
                <h2><span>e</span>-shopper</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
              </div>
            </div>
            <div class="col-sm-7">
              <div class="col-sm-3">
                <div class="video-gallery text-center">
                  <a href="#">
                    <div class="iframe-img">
                      <%= image_tag("home/iframe1.png") %>
                    </div>
                    <div class="overlay-icon">
                      <i class="fa fa-play-circle-o"></i>
                    </div>
                  </a>
                  <p>Circle of Hands</p>
                  <h2>24 DEC 2014</h2>
                </div>
              </div>

              <div class="col-sm-3">
                <div class="video-gallery text-center">
                  <a href="#">
                    <div class="iframe-img">
                      <%= image_tag("home/iframe2.png") %>
                    </div>
                    <div class="overlay-icon">
                      <i class="fa fa-play-circle-o"></i>
                    </div>
                  </a>
                  <p>Circle of Hands</p>
                  <h2>24 DEC 2014</h2>
                </div>
              </div>

              <div class="col-sm-3">
                <div class="video-gallery text-center">
                  <a href="#">
                    <div class="iframe-img">
                      <%= image_tag("home/iframe3.png") %>
                    </div>
                    <div class="overlay-icon">
                      <i class="fa fa-play-circle-o"></i>
                    </div>
                  </a>
                  <p>Circle of Hands</p>
                  <h2>24 DEC 2014</h2>
                </div>
              </div>

              <div class="col-sm-3">
                <div class="video-gallery text-center">
                  <a href="#">
                    <div class="iframe-img">
                      <%= image_tag("home/iframe4.png") %>
                    </div>
                    <div class="overlay-icon">
                      <i class="fa fa-play-circle-o"></i>
                    </div>
                  </a>
                  <p>Circle of Hands</p>
                  <h2>24 DEC 2014</h2>
                </div>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="address">
                <img src="/assets/home/map.png" alt="" />
                <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="footer-widget">
        <div class="container">
          <div class="row">
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>Service</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li><a href="#">Online Help</a></li>
                  <li><a href="#">Contact Us</a></li>
                  <li><a href="#">Order Status</a></li>
                  <li><a href="#">Change Location</a></li>
                  <li><a href="#">FAQ’s</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>Quock Shop</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li><a href="#">T-Shirt</a></li>
                  <li><a href="#">Mens</a></li>
                  <li><a href="#">Womens</a></li>
                  <li><a href="#">Gift Cards</a></li>
                  <li><a href="#">Shoes</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>Policies</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li><a href="#">Terms of Use</a></li>
                  <li><a href="#">Privecy Policy</a></li>
                  <li><a href="#">Refund Policy</a></li>
                  <li><a href="#">Billing System</a></li>
                  <li><a href="#">Ticket System</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="single-widget">
                <h2>About Shopper</h2>
                <ul class="nav nav-pills nav-stacked">
                  <li><a href="#">Company Information</a></li>
                  <li><a href="#">Careers</a></li>
                  <li><a href="#">Store Location</a></li>
                  <li><a href="#">Affillate Program</a></li>
                  <li><a href="#">Copyright</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-3 col-sm-offset-1">
              <div class="single-widget">
                <h2>About Shopper</h2>
                <form action="#" class="searchform">
                  <input type="text" placeholder="Your email address" />
                  <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                  <p>Get the most recent updates from <br />our site and be updated your self...</p>
                </form>
              </div>
            </div>

          </div>
        </div>
      </div>

      <div class="footer-bottom">
        <div class="container">
          <div class="row">
            <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
            <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>